set.seed(2026)
toy <- section5_problem_5a_fish(stocks = c("LOSALM","CHMBLN","IMNAHA"), strats = c("S1","S2","S3"), nfish = 120L)
stopifnot(all(c("FishWH","FishDat") %in% names(toy)))
wh <- section5_problem_5b_fish(toy$FishWH)
fd <- section5_problem_5c_fish(toy$FishDat)
stopifnot(nrow(wh) == nrow(toy$FishWH), nrow(fd) == nrow(toy$FishDat))
th <- section5_problem_5d_fish(wh, fd)
stopifnot(is.numeric(th), length(th) == 1)
bs <- section5_problem_5e_fish(toy$FishWH, toy$FishDat, boots = 500L)
stopifnot(length(bs$ci) == 2L)
section5_problem_5f_fish()
